// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StreamingPlatform.Domain.Models
{
    public partial class PlaylistItem
    {
        public int Id { get; set; }
        public int PlaylistId { get; set; }
        public int SongId { get; set; }

        public virtual PlayList Playlist { get; set; }
    }
}