// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StreamingPlatform.Domain.Models
{
    public partial class PlayList
    {
        public PlayList()
        {
            PlaylistItem = new HashSet<PlaylistItem>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        public string Name { get; set; }

        public virtual Member Member { get; set; }
        public virtual ICollection<PlaylistItem> PlaylistItem { get; set; }
    }
}