// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StreamingPlatform.Domain.Models;

public partial class SingerAndSongRelation
{
    public int Id { get; set; }

    public int SongId { get; set; }

    public int SingerId { get; set; }

    public string SingerName { get; set; }
}